name = "essay-checker"
main = "worker.js"
compatibility_date = "2024-12-16"

[env.production]
routes = [
  { pattern = "essayapi.yossy-ac.workers.dev/*", zone_name = "yossy-ac.workers.dev" }
]
vars = { ENVIRONMENT = "production" }
